### ISSUE TITLE
cross build img ?

### ISSUE THREAD

**Issue by kapouer** [alpernebbi/depthcharge-tools#4]
Hi,
i wonder if it's possible to
```
depthchargectl build --board=veyron_speedy --output veyron.img
```
from another machine.

**Comment by alpernebbi** [comment]
It should work, but you would need to specify kernel, initramfs, fdtdir/dtbs, root, and kernel cmdline args to get something that actually boots. I remember using `--board kevin` from an amd64 laptop to pack e.g. Arch Linux ARM, Debian Installer.

OTOH, I never tested this on anything except `kevin`. I can only hope my best guesses work on other boards.

**Comment by kapouer** [comment]
ok, i suppose it's easier to bootstrap the img from a qemu environment.

**Comment by alpernebbi** [comment]
I ended up adding a global `--root` argument that can be pointed to chroot mountpoints. So `depthchargectl build --board speedy-libreboot --root /mnt --output veyron.img` from another computer would build an image for veyron and that installation. Even `depthchargectl write` should work and write to the disk the moutpoint is for.
